void unos(void);
void pretraga(void);
void prikaziTabelu(void);
int izracunajRazlikuGolova(void);
void sortiraj(void);
void igrajMec(void);
void izlaz(void);
int dodaj_ekipu(struct tim);
void ucitaj_podatke(void);
void sacuvaj_podatke(void);
